[project]
name = 'Carbon-Credit-Trading-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.carbon-credit]
path = 'contracts/carbon-credit.clar'
clarity_version = 2
epoch = 2.5

[contracts.emissions-data]
path = 'contracts/emissions-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.offset-nft]
path = 'contracts/offset-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.offset-project]
path = 'contracts/offset-project.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
